import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css';



// const link = "http://192.168.1.251:3000/api/hello";

const link2 ="https://jsonplaceholder.typicode.com/todos";

















export default function Home({data}) {
















  return (
    <div className={styles.container}>
      <Head>
        <title>Lucy API</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>data</h1>
        <hr />

        {console.log(data)}

        {data.map(item => {
          return <p>{item.title}</p>

        })}



    





        
        
        


      </main>


  



    </div>
  )
}






export async function getServerSideProps() {
  const res = await fetch(link2);
  const data = await res.json();
  return {props:{data}}

}























