import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { link} from './data';

















export default function Home({data}) {
















  return (
    <div className={styles.container}>
      <Head>
        <title>Lucy API</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>data</h1>
        <hr />




        {data.map(item=> {
          return <>
          
          <p>{item.name}  {' >> '} {item.age} </p>
          
          </>
        })}




    





        
        
        


      </main>


  



    </div>
  )
}






export async function getServerSideProps() {
  const res = await fetch(link);
  const data = await res.json();
  return {props:{data}}

}























